--> import "Numpy" \
--> Create Vector


In [28]:
import numpy as np
# ------------------1st-row --------------- 2nd-row ----------
matrix = np.array([[1, 3, 5, 7, 9], [2, 4, 6, 8, 10]])

Accessing elements


In [29]:
# accessing element
print(matrix[:1])  # 1st row
print(matrix[1, 4])  # 2nd row 5th element
print(matrix[0:2, 4])  # 5th element of each row

[[1 3 5 7 9]]
10
[ 9 10]


accessing elements from last


In [30]:
print(matrix[-1])  # last element or row
print(matrix[0:, -3])  # last 3rd element

[ 2  4  6  8 10]
[5 6]


Matrix


In [31]:
# number of rows and columns
print(f"Number of rows and column: {matrix.shape}") 

# number of elements
print(f"Number of elements: {matrix.size}")

# dimension of matrix
print(f"Number of dimension of matrix: {matrix.ndim}")

Number of rows and column: (2, 5)
Number of elements: 10
Number of dimension of matrix: 2


MIN & MAX

In [32]:
# Max number in matrix
print(np.max(matrix)) 

# Min number in matrix
print(np.min(matrix))

10
1


Calculate "Average"

In [33]:
# average of first row
print(f"{matrix[0]} =  {np.mean(matrix[0])}") 

# average of last row
print(f"{matrix[1]} = {np.mean(matrix[1])}") 

# average of whole matrix
print(f"{np.mean(matrix)}")




[1 3 5 7 9] =  5.0
[ 2  4  6  8 10] = 6.0
5.5


Reshape

In [34]:
print(matrix.reshape(5, 2)) # (row, col)
print(matrix.reshape(10)) # in 1 row -- 1_dimensional
print(matrix.reshape(-1)) # in 1 row -- 1_dimensional
print(matrix.flatten()) # in 1 row -- 1_dimensional

[[ 1  3]
 [ 5  7]
 [ 9  2]
 [ 4  6]
 [ 8 10]]
[ 1  3  5  7  9  2  4  6  8 10]
[ 1  3  5  7  9  2  4  6  8 10]
[ 1  3  5  7  9  2  4  6  8 10]


TRANSPOSE

In [35]:
print(matrix.T) 

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


DIGONAL

In [36]:
print(matrix.diagonal())

[1 4]


DOT PRODUCT

In [37]:
vector_1 = np.array([1,2,3])
vector_2 = np.array([4,5,6])

print(np.dot(vector_1, vector_2))

32


ADDING, SUBTRACTIN AND MULTIPLYING MATRICES

In [38]:
matrix_1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_2 = np.array([[2, 4, 6], [8, 10, 6], [4, 2, 0]])

print(f"add: {np.add(matrix_1, matrix_2)}")
print(f"subtract: {np.subtract(matrix_1, matrix_2)}")
print(f"multipl: - element wise \n{matrix_1 * matrix_2}")
print(f"mat_mul(row column wise): \n{np.matmul(matrix_1, matrix_2)}")

add: [[ 3  6  9]
 [12 15 12]
 [11 10  9]]
subtract: [[-1 -2 -3]
 [-4 -5  0]
 [ 3  6  9]]
multipl: - element wise 
[[ 2  8 18]
 [32 50 36]
 [28 16  0]]
mat_mul(row column wise): 
[[ 30  30  18]
 [ 72  78  54]
 [114 126  90]]


Zeros and ONES



In [39]:
print(f"Zeros: \n{np.zeros([4, 4])}")
print(f"\nOnes: \n{np.ones([4, 4])}")

Zeros: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Random Values

In [40]:
# genrate 3 random numbers between 0 and 10
print(np.random.randint(0, 11, 3))

# genrate 
print(np.random.normal(1.0, 2.0, 4))


[10  8  0]
[-0.12132377  4.70952358  1.72185296 -0.2856695 ]
